### PR TITLE
add flake8 linter and AutoPEP8 formatter

### PR DESCRIPTION
**Pull request by krokrob**
this fixes https://github.com/lewagon/data-setup/issues/23 @ssaunier please review

### CODE REVIEW

**Comment by ssaunier** [comment]
- What about Glovebox? cf https://github.com/lewagon/data-runner/blob/master/Dockerfile#L5
- What about the `Makefile` in `data-challenges`? cf https://github.com/lewagon/data-challenges/blob/master/01-Python/01-Programming-Basics/01-Sum-Of-Three/Makefile#L4

**Comment by krokrob** [comment]
We don't use `flake8` for syntax testing atm but it is a good linter for students inside their code ediitor. We will change `pylint` for flake8` in Q2 I think.

**Comment by krokrob** [comment]
I forgot to mention you in https://github.com/lewagon/data-setup/pull/42

**Comment by ssaunier** [comment]
The risk of doing 50% of that change is that `flake8` in Sublime Text will say something while the `pylint` through `make` will say another, don't you think it'll be even more confusing for students?

**Comment by krokrob** [comment]
`pylint` is much more "lazy" than `flake8`,  as it considers devs know how to use code formatter like `black` or `autoPEP8`. Our students still need linter as they are still programming learner. There won't be contradictory syntax error between the 2 frameworks.

**Pull request merged**
