### PR TITLE
[pyenv] handle the PATH for pyenv

### PR DESCRIPTION
**Pull request by gmanchon**
this PR adds a `~/.profile` file to the setup in order to handle the PATH manipulations for pyenv

## context

pyenv 2.0.0 introduced around May 2021 a [breaking change](https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md) where the PATH is [no longer handled](https://github.com/pyenv/pyenv/issues/1649#issuecomment-694388530) by the `pyenv init`command

the solution proposed when running the `pyenv init` command is to handle the PATH for pyenv manually in the `~/.profile` file (where the user custom PATH manipulations are supposed to take place, not in the `~/.zshrc` file) :

``` bash
# (The below instructions are intended for common
# shell setups. See the README for more guidance
# if they don't apply and/or don't work for you.)

# Add pyenv executable to PATH and
# enable shims by adding the following
# to ~/.profile and ~/.zprofile:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Load pyenv into the shell by adding
# the following to ~/.zshrc:

eval "$(pyenv init -)"

# Make sure to restart your entire logon session
# for changes to profile files to take effect.
```

### CODE REVIEW

**Review by krokrob — COMMENTED** [review]
Cool! How is it linked to the `~/.profile` of our students?

**Comment by gmanchon** [comment]
@krokrob looks like `https://github.com/lewagon/dotfiles/blob/master/install.sh` does that for us. I ran the script manually to verify and it seems to be the work correctly (almost). Basically it creates a symlink version of all the files at the root of dotfiles in the home of the user.

The following paragraph of the file reads (approximately) as follows afaik :
- iterate on all the files in the dotfiles dir (install.sh is supposedly ran from the dotfiles dir)
  - if the file is not a directory
    - define target file path in the home dir as . + filename
    - if the target is not a .sh script or README.md or .sublime-settings
      - create a backup of the file with corresponding name + .backup in the home
        ☝️ btw this part seems to fail as no .backup files are generated in my home as I successively run the script
      - then create a symlink to the file in the dotfiles (git controlled) from the corresp .file in the home dir

``` bash
#!/bin/zsh
for name in *; do
  if [ ! -d "$name" ]; then
    target="$HOME/.$name"
    if [[ ! "$name" =~ '\.sh$' ]] && [ "$name" != 'README.md' ] && [[ ! "$name" =~ '\.sublime-settings$' ]]; then
      backup $target

      if [ ! -e "$target" ]; then
        echo "-----> Symlinking your new $target"
        ln -s "$PWD/$name" "$target"
      fi
    fi
  fi
done
```

I have not tried to bullet proof validate the whole thing - appart from the `type -a pyenv > /dev/null &&` which makes sure that the students of the web dev bootcamp that do not have `pyenv` installed are not impacted by the setup, I was kind of hoping for a blind validation 😉 😁

No really someone should probably bullet proof this, is there someone who is already up to speed on this ?

**Comment by gmanchon** [comment]
ps : looks like rerunning `install.sh` does the trick for students having already completed the setup...

**Comment by krokrob** [comment]
> @krokrob looks like `https://github.com/lewagon/dotfiles/blob/master/install.sh` does that for us. I ran the script manually to verify and it seems to do the job correctly. Basically it creates a symlink to all the files at the root of dotfiles in the home of the user.
> 
> The following paragraph of the file reads (approximately) as follows afaik :
> 
>     * iterate on all the files in the dotfiles dir (install.sh is supposedly ran from the dotfiles dir)
>       
>       * if the file is not a directory
>         
>         * define target file path in the home dir as . + filename
>         * if the target is not a .sh script or README.md or .sublime-settings
>           
>           * create a backup of the file with corresponding name + .backup in the home
>             ☝️ only backup if the file is a pure file (not a symlink)
>           * then create a symlink to the file in the dotfiles (git controlled) from the corresp .file in the home dir
>             ☝️ if the target does not exist - which should not be the case (unless you are evil an intentionally created a non symlink .file and a .file.backup previously to running the script)
> 
> 
> ```shell
> #!/bin/zsh
> for name in *; do
>   if [ ! -d "$name" ]; then
>     target="$HOME/.$name"
>     if [[ ! "$name" =~ '\.sh$' ]] && [ "$name" != 'README.md' ] && [[ ! "$name" =~ '\.sublime-settings$' ]]; then
>       backup $target
> 
>       if [ ! -e "$target" ]; then
>         echo "-----> Symlinking your new $target"
>         ln -s "$PWD/$name" "$target"
>       fi
>     fi
>   fi
> done
> ```
> 
> I have not tried to bullet proof validate the whole thing - appart from the `type -a pyenv > /dev/null &&` which makes sure that the students of the web dev bootcamp that do not have `pyenv` installed are not impacted by the setup, I was kind of hoping for a blind validation 😉 😁
> 
> No really someone should probably bullet proof this (or agree to creating a new `.profile` file handling the PATH related operations - which could be extracted from the `.zshrc` ?), is there someone who is already up to speed on this ?

Crystal clear, thanks!

**Pull request merged**
